export const irrigationDetails = {
    "Cotton": { minMoisture: 45, irrigationAmount: "20-30 mm" },
    "Horsegram": { minMoisture: 35, irrigationAmount: "15-25 mm" },
    "Jowar": { minMoisture: 40, irrigationAmount: "20-30 mm" },
    "Maize": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Moong": { minMoisture: 40, irrigationAmount: "15-25 mm" },
    "Ragi": { minMoisture: 35, irrigationAmount: "20-30 mm" },
    "Rice": { minMoisture: 75, irrigationAmount: "Maintain flooded conditions" },
    "Sunflower": { minMoisture: 50, irrigationAmount: "25-35 mm" },
    "Wheat": { minMoisture: 45, irrigationAmount: "20-30 mm" },
    "Sesamum": { minMoisture: 35, irrigationAmount: "15-25 mm" },
    "Soybean": { minMoisture: 50, irrigationAmount: "25-35 mm" },
    "Rapeseed": { minMoisture: 45, irrigationAmount: "20-30 mm" },
    "Jute": { minMoisture: 60, irrigationAmount: "30-40 mm" },
    "Arecanut": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Onion": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Potato": { minMoisture: 65, irrigationAmount: "30-40 mm" },
    "Sweet Potato": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Tapioca": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Turmeric": { minMoisture: 60, irrigationAmount: "30-40 mm" },
    "Barley": { minMoisture: 45, irrigationAmount: "20-30 mm" },
    "Banana": { minMoisture: 65, irrigationAmount: "30-40 mm" },
    "Coriander": { minMoisture: 45, irrigationAmount: "20-30 mm" },
    "Garlic": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Black Pepper": { minMoisture: 60, irrigationAmount: "30-40 mm" },
    "Cardamom": { minMoisture: 65, irrigationAmount: "30-40 mm" },
    "Cashew Nuts": { minMoisture: 40, irrigationAmount: "15-25 mm" },
    "Blackgram": { minMoisture: 40, irrigationAmount: "15-25 mm" },
    "Coffee": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Ladyfinger": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Brinjal": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Cucumber": { minMoisture: 65, irrigationAmount: "30-40 mm" },
    "Grapes": { minMoisture: 45, irrigationAmount: "20-30 mm" },
    "Mango": { minMoisture: 45, irrigationAmount: "20-30 mm" },
    "Orange": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Papaya": { minMoisture: 65, irrigationAmount: "30-40 mm" },
    "Tomato": { minMoisture: 60, irrigationAmount: "30-40 mm" },
    "Cabbage": { minMoisture: 65, irrigationAmount: "30-40 mm" },
    "Bottle Gourd": { minMoisture: 60, irrigationAmount: "30-40 mm" },
    "Pineapple": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Carrot": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Radish": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Bitter Gourd": { minMoisture: 55, irrigationAmount: "25-35 mm" },
    "Drumstick": { minMoisture: 40, irrigationAmount: "15-25 mm" },
    "Jackfruit": { minMoisture: 55, irrigationAmount: "25-35 mm" }
};